### ISSUE TITLE
AttributeError: 'PyTgCalls' object has no attribute 'run'

### ISSUE THREAD

**Issue by VirusIn0014** [TeamDaisyX/DaisyXMusic-Beta#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/DaisyXMusic/__main__.py", line 22, in <module>
    from DaisyXMusic.services.callsmusic import run
  File "/app/DaisyXMusic/services/callsmusic/__init__.py", line 2, in <module>
    from DaisyXMusic.services.callsmusic.callsmusic import pytgcalls, run
  File "/app/DaisyXMusic/services/callsmusic/callsmusic.py", line 38, in <module>
    run = pytgcalls.run
AttributeError: 'PyTgCalls' object has no attribute 'run'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/DaisyXMusic/__main__.py", line 22, in <module>
    from DaisyXMusic.services.callsmusic import run
  File "/app/DaisyXMusic/services/callsmusic/__init__.py", line 2, in <module>
    from DaisyXMusic.services.callsmusic.callsmusic import pytgcalls, run
  File "/app/DaisyXMusic/services/callsmusic/callsmusic.py", line 38, in <module>
    run = pytgcalls.run
AttributeError: 'PyTgCalls' object has no attribute 'run'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/DaisyXMusic/__main__.py", line 22, in <module>
    from DaisyXMusic.services.callsmusic import run
  File "/app/DaisyXMusic/services/callsmusic/__init__.py", line 2, in <module>
    from DaisyXMusic.services.callsmusic.callsmusic import pytgcalls, run
  File "/app/DaisyXMusic/services/callsmusic/callsmusic.py", line 38, in <module>
    run = pytgcalls.run
AttributeError: 'PyTgCalls' object has no attribute 'run'

**Comment by Technical-Hunter** [comment]
Thanks this is PyTgCalls Error this will fix after stable update of PyTgCalls

**Comment by Technical-Hunter** [comment]
Hey Now I am fixed that error can you deploy it again🙂
